name: kangaroo_business_app_sdk_web
description: Kangaroo App SDK Flutter plugin web module.
version: 0.0.1
homepage: https://kangaroorewards.com/
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  kangaroo_business_app_sdk_platform_interface:
#    git:
#      url: https://github.com/paulkangaroo/kangaroo-app-sdk-flutter-plugin.git
#      path: kangaroo_business_app_sdk_platform_interface
#      ref: multi-module
    path: ../kangaroo_business_app_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: KangarooAppSDKWebFlutterPlugin
        fileName: kangaroo_business_app_sdk_web.dart